# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'cd-inke' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cd-inke

pod 'AFNetworking', '~> 3.1.0'

pod 'SDWebImage', '~> 3.8.1'

pod 'Masonry', '~> 1.0.1'

pod 'YYKit', '~> 1.0.7'

pod 'MJExtension', '~> 3.0.10'


  target 'cd-inkeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cd-inkeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
